[tool.black]
line-length = 200
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''(^|/)(
    \.eggs/|
    \.git/|
    \.hg/|
    \.mypy_cache/|
    \.nox/|
    \.tox/|
    \.venv/|
    _build/|
    build/|
    dist/
)'''